# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install dependencies without running scripts to skip postinstall if any issues
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not strictly necessary for MCP over stdio, but for clarity)
# EXPOSE 8080

# Command to run the MCP server
CMD [ "npm", "start" ]
